server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: review
          uri: lb://review-service
          predicates:
            - Path=/review/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
