server:
  port: 0
  servlet:
    context-path: /books


management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

spring:

  application.name: service-books
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bookstore
    username: service_books
    password: service-book
  sql.init.mode: always

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate.ddl-auto: validate
  jackson:
    deserialization:
      fail-on-ignored-properties: false
    serialization:
      indent-output: true
      write-date-keys-as-timestamps: true
      write-bigdecimal-as-plain: true
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

logging.pattern.console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}