server:
  port: 8080
  servlet:
    context-path: /user

management:
  health:
    livenessState.enabled: true
    readinessState.enabled: true
  endpoint.health.probes.enabled: true

spring:
  application:
    name: backend-user
  jackson:
    deserialization:
      fail-on-ignored-properties: false
    serialization:
      indent-output: false
      write-date-keys-as-timestamps: false
      write-bigdecimal-as-plain: true


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
#  level:
#    org:
#      springframework : DEBUG
#      hibernate: DEBUG
#    com.netflix.discovery: DEBUG