version: '3.8'

services:
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"

  gateway:
    build: ./gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server

  review:
    build: ./review-service
    expose:
      - "8080"
    depends_on:
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=default

networks:
  default:
