spring:
  cloud:
    function:
      definition:  stringSupplier;stringConsumer
    stream:
      bindings:
        stringSupplier-out-0:
          destination: greetings-topic
        stringConsumer-in-0:
          destination: greetings-topic
      poller:
        fixed-delay: 5000
      default-binder: rabbit
  rabbitmq:
    host: localhost
    port: 5672

logging:
  level:
    root: INFO