spring:
  cloud:
    function:
      definition:  messageConsumer
    stream:
      bindings:
        test-out:
          destination: test-queue
        messageConsumer-in-0:
          destination: test-queue
      poller:
        fixed-delay: 3000
      default-binder: rabbit
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    root: INFO